### PR TITLE
fix: update scripts from example.cii 

### LINKED ISSUE #150: Take some changes from example.cii
**Describe the Improvement:**  
Want to update scripts with some of the improvements from https://github.com/devlinjunker/example.cii

**Steps:**  
  1.    Update `scripts/` directory

**Additional Context and Links:**  
N/A

**Testing:**  
N/A

### PR DESCRIPTION
**Pull request by devlinjunker**
**Description:** 
Add Linting changes from https://github.com/devlinjunker/example.cii

**Related:** 
#150 
https://github.com/devlinjunker/example.cii/pull/10

**Visual:** 
N/A

**TODO:**
 - [x] Updated README documents
 - [x] Complete PR Body

### CODE REVIEW

File: scripts/hooks/internal/prefix-list.sh [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+  # merge labels.yaml with hardcoded
+  local PREFIXES=( "${LABEL_TYPES[*]}" "${OTHER_TYPES[*]}" )
+
+  echo "${PREFIXES[*]}"
+
+}
+
+## For BATS testing
+mock() {
```
Comment (devlinjunker) [inline scripts/hooks/internal/prefix-list.sh]: remove this?

**Comment by devlinjunker** [comment]
!merge
